# Generated by Django 3.2.11 on 2022-01-20 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City_Geo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geo_name', models.CharField(max_length=100, verbose_name='City Name')),
                ('geo_lat', models.CharField(max_length=20, verbose_name='Geo lat')),
                ('geo_lon', models.CharField(max_length=20, verbose_name='Geo lon')),
                ('geo_description', models.CharField(max_length=200, verbose_name='Description')),
            ],
        ),
    ]
